Repository adopted-ember-addons/ember-changeset-validations, pull requests merged in 2021-07, with the labels that each got.

#308 Bump ember-validators
  package-lock.json
  package.json
Labels: enhancement

#309 Fix Ember tracking issue on set
  package-lock.json
  package.json
Labels: bug

#312 Bugfix: validate on render without backtracking Ember assertion
  package-lock.json
  package.json
Labels: bug, enhancement

#305 fix(presence on): allow for nested keys to be used in `validatePresence` -> `on`
  addon/validators/presence.js
Labels: bug, enhancement
