Repository adopted-ember-addons/ember-changeset-validations, pull requests merged in 2025-04, with the labels that each got.

#371 Switch addon configuration from environment.js to @embroider/macros
  .github/workflows/ci.yml
  .gitignore
  README.md
  addon/.gitkeep
  addon/index.js
  addon/utils/get-messages.js
  addon/utils/messages.js
  addon/utils/validation-errors.js
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app-raw-output/app/app.ts
  test-app-raw-output/app/config/environment.d.ts
  test-app-raw-output/app/index.html
  test-app-raw-output/app/router.ts
  test-app-raw-output/app/styles/app.css
  test-app-raw-output/app/templates/application.hbs
  test-app-raw-output/config/ember-cli-update.json
  test-app-raw-output/config/environment.js
  test-app-raw-output/config/optional-features.json
  test-app-raw-output/config/targets.js
  test-app-raw-output/ember-cli-build.js
  test-app-raw-output/package.json
  test-app-raw-output/testem.js
  test-app-raw-output/tests/index.html
  test-app-raw-output/tests/test-helper.ts
  test-app-raw-output/tests/unit/utils/validation-errors-test.js
  test-app-raw-output/tsconfig.json
  test-app-raw-output/types/global.d.ts
  tests/integration/components/validation-errors-test.js
  tests/unit/.gitkeep
  tests/unit/helpers/changeset-test.js
  tests/unit/utils/get-messages-test.js
  tests/unit/utils/validation-errors-test.js
Labels: breaking

#374 Drop support for Ember.js versions below 4.8
  .github/workflows/ci.yml
  README.md
  package.json
  tests/dummy/config/ember-try.js
Labels: breaking

#375 Vanilla Prettier Setup
  .prettierrc.cjs
  .stylelintignore
  .stylelintrc.js
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app-raw-output/app/index.html
  tests/dummy/app/components/address-book.hbs
  tests/dummy/app/components/foo-bar.hbs
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/index.html
Labels: internal

#377 Bump ember-validators to v5
  package.json
  pnpm-lock.yaml
Labels: enhancement

#379 Add push-dist workflow for testing pre-release updates
  .github/workflows/push-dist.yml
Labels: internal

#380 Fix broken urls in readme
  README.md
Labels: documentation

#381 Disable declarations folder generation
  rollup.config.mjs
Labels: bug
